name: Pipeline
run-name: ${{ github.ref }} on ${{ github.repository }} is being built and tested out Github actions
on:
  push:
jobs:
  Pipeline-Linux:
    strategy:
      fail-fast: false
      matrix:
        compiler: ["GCC", "Clang"]
        config: ["Debug", "Release"]
        build_shared: [0, 1]
        include:
          - compiler: "GCC"
            C: gcc
            CXX: g++
          - compiler: "Clang"
            C: clang
            CXX: clang++
    run-ons: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4