name: Pipeline
run-name: ${{ github.ref }} on ${{ github.repository }} is being built and tested out Github actions
on:
  push:
jobs:
  Pipeline-Linux:
    strategy:
      fail-fast: false
      matrix:
          compiler: ["gcc", "clang"]
          config: ["Debug", "Release"]
          build_shared: [0, 1]
          include: 
            - compiler: "gcc"
              C: gcc
              CXX: g++
            - compiler: "clang"
              C: clang
              CXX: clang++
            - build_shared: 0
              build_type: "Static"
            - build_shared: 1
              build_type: "Shared"
            
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate project with examples with ${{ matrix.build_type }} libraries
        run: cmake -S ./ -B ./build -DBUILD_TEXT_RENDER_ENGINE_EXAMPLES=1 -DBUILD_SHARED_LIBS=${{ matrix.build_shared }} -DCMAKE_C_COMPILER=${{ matrix.C }} -DCMAKE_CXX_COMPILER=${{ matrix.CXX }} -G "Unix Makefiles"
      - name: Build project in ${{ matrix.config }} configuration
        run : cmake --build build --config ${{ matrix.config }}
      - name: Upload examples
        uses: actions/upload-artifact@v4
        with:
          name: examples-ubuntu-${{matrix.compiler}}-${{ matrix.config }}-${{ matrix.build_type }}
          path: build/out
  Pipleline-Windows:
    strategy:
      fail-fast: false
      matrix:
          compiler: ["MSVC", "gcc", "clang"]
          config: ["Debug", "Release"]
          build_shared: [0, 1]
          include: 
            - compiler: "gcc"
              C: gcc
              CXX: g++
            - compiler: "clang"
              C: clang-cl
              CXX: clang-cl
            - build_shared: 0
              build_type: "Static"
            - build_shared: 1
              build_type: "Shared"
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate project with examples with ${{ matrix.build_type }} libraries for Unix Makefiles
        if: ${{ matrix.compiler != 'MSVC' }}
        run: cmake -S ./ -B ./build -DBUILD_TEXT_RENDER_ENGINE_EXAMPLES=1 -DBUILD_SHARED_LIBS=${{ matrix.build_shared }} -DCMAKE_C_COMPILER=${{ matrix.C }} -DCMAKE_CXX_COMPILER=${{ matrix.CXX }} -G "Unix Makefiles"
      - name: Generate project with examples with ${{ matrix.build_type }} libraries for Visual Studio
        if: ${{ matrix.compiler == 'MSVC' }}
        run: cmake -S ./ -B ./build -DRUN_TEST=1 -DBUILD_ENGINE_EXAMPLES=1 -DBUILD_SHARED_LIBS=${{ matrix.build_shared }}
      - name: Build project in ${{ matrix.config }} configuration
        run : cmake --build build --config ${{ matrix.config }}
      - name: Upload examples
        uses: actions/upload-artifact@v4
        with:
          name: examples-windows-${{matrix.compiler}}-${{ matrix.config }}-${{ matrix.build_type }}
          path: build/out
  Merge-Artifacts:
    runs-on: ubuntu-latest
    needs: Pipeline-Linux
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: Examples-Ubuntu
          pattern: examples-ubuntu-*
          separate-directories: true
          delete-merged: true
